"""initial schema

Revision ID: a7dea5c70856
Revises: 
Create Date: 2026-06-19 13:59:50.207607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dea5c70856'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_statuses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_ok', sa.String(length=40), nullable=False),
    sa.Column('fails', sa.Integer(), nullable=False),
    sa.Column('avg_ms', sa.Integer(), nullable=False),
    sa.Column('trust', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_logs',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.String(length=10), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('work_type', sa.String(length=40), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=False),
    sa.Column('decided_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('loc', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('work_type', sa.String(length=30), nullable=False),
    sa.Column('project_type', sa.String(length=30), nullable=False),
    sa.Column('river_work_flag', sa.Boolean(), nullable=False),
    sa.Column('river_state', sa.String(length=20), nullable=False),
    sa.Column('river_note', sa.String(length=100), nullable=False),
    sa.Column('flood_info', sa.Boolean(), nullable=False),
    sa.Column('manager', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_types',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('rel', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_plans',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.String(length=10), nullable=False),
    sa.Column('work_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('planned_start', sa.String(length=40), nullable=False),
    sa.Column('planned_end', sa.String(length=40), nullable=False),
    sa.Column('contractor', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_plans')
    op.drop_table('stations')
    op.drop_table('work_types')
    op.drop_table('sites')
    op.drop_table('decision_logs')
    op.drop_table('data_source_statuses')
    # ### end Alembic commands ###
